Develop
IrynaZazyba/Certificates pull request #1
Opened 2020-10-28 13:23 UTC by IrynaZazyba

2020-10-28 19:49 UTC, aolshevskiy requested changes
General review notes:
1. Please remove .class files from repository. This is binary artifacts that should not be commited to version control
1. Connection pooling is required
1. NIT: Error message localization is required

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/java/com/epam/esm/dao/impl/CertificateDaoImpl.java
> +    private String createFilterQuery(Filter filter) {
This method is vulnureable to SQL injection. Please use SQL parameters here.

2020-10-28 19:49 UTC, aolshevskiy commented on src/main/java/com/epam/esm/App.java
> +public class App {
Do we really need this?

2020-10-28 19:49 UTC, aolshevskiy commented on pom.xml
>  <?xml version="1.0" encoding="UTF-8" standalone="no"?>
Why do we have a project with a single module?

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/java/com/epam/esm/dao/impl/CertificateDaoImpl.java
> +        return Objects.requireNonNull(keyHolder.getKey()).longValue();
Just interested. In what situation does `keyHolder.getKey()` returns `null`?

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/java/com/epam/esm/dao/impl/TagDaoImpl.java
> +        return Objects.requireNonNull(keyHolder.getKey()).longValue();
Same as above.

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/java/com/epam/esm/domain/Certificate.java
> +    private LocalDateTime createDate;
NIT: I feel like Instant should be used here, but this is a point for discussion.

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/java/com/epam/esm/domain/Filter.java
> +    private String searchDescription;
NIT: `search` prefix could be removed for these fields.

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/java/com/epam/esm/domain/Tag.java
> +    private Set<Certificate> certificates = new HashSet<>();
Using `Set` here is with default `Certificate.equals` implementation might not be the best decision.

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/java/com/epam/esm/dto/FilterDto.java
> +    private String searchDescription;
Same as above.

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +        Certificate certificate = certificateMapper.toModel(certificateDto);
Should also be validated as in `createCertificate`?

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +        if (!Objects.isNull(tags)) {
Are you sure this check is necessary?

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +            throw new InvalidUserDataException("Invalid user data");
In my opinion this error message is not comprehensive enough.

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/java/com/epam/esm/dao/impl/TagDaoImpl.java
> +            throw new ResourceNotFoundException("Resource not found", e, id);
NIT: Resource is REST concept that don't belong to data access layer. I'd personally remove this exceptions from here and handle'em on service or even controller layer.

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/java/com/epam/esm/service/impl/TagServiceImpl.java
> +            return tagDao.insertTag(tagMapper.toModelWithoutCertificate(tag));
Exception handlers are for exceptional situations. Let's better check if tag already exists before inserting it or use some kind of upsert operation to do it in one query.

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/java/com/epam/esm/service/validation/impl/CertificateValidatorImpl.java
> +public class CertificateValidatorImpl implements Validator<CertificateDto> {
NIT: Spring has it's own validation infrastructure for that. See https://docs.spring.io/spring-framework/docs/3.2.x/spring-framework-reference/html/validation.html .

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/resources/schema.sql
> +  `duration` int(11) DEFAULT NULL
Should all the fields really be `NULL`?

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/main/resources/schema.sql
> +  `name` varchar(45) DEFAULT NULL
Why don't make name `NOT NULL`?

2020-10-28 19:49 UTC, aolshevskiy commented on api/src/test/java/com/epam/esm/service/CertificateServiceTest.java
> +    }
Mockito verifications are expected to happen after calling unit under test.

2020-10-29 09:02 UTC, Pickle9 approved these changes
Generally, everything is fine. But there are several places for additional changes.

Common notes: 
Use 'gitignore' for ignoring all unused files and folders (like target)
Use Connection Pool (like a HikariCP)

2020-10-29 09:02 UTC, Pickle9 commented on api/pom.xml
> +            <version>4.0.1</version>
It would be more consistent to move all versions values into the properties

2020-10-29 09:02 UTC, Pickle9 commented on api/src/main/java/com/epam/esm/config/SpringConfig.java
> +@PropertySources({@PropertySource("classpath:application-${spring.profiles.active}.properties")})
You have just a single source value, so, @PropertySources annotation is excess in this case.

2020-10-29 09:02 UTC, Pickle9 commented on api/src/main/java/com/epam/esm/config/SpringConfig.java
> +    private final static int DEFAULT_INITIAL_SIZE = 3;
'static' should be used before 'final' according to the Code Convention

2020-10-29 09:02 UTC, Pickle9 commented on api/src/main/java/com/epam/esm/controller/CertificateController.java
> +    @RequestMapping(value = "/{id}", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
It's not critical, but just try to use the same format everywhere, e.g. GetMapping or RequestMapping

2020-10-29 09:02 UTC, Pickle9 commented on api/src/main/java/com/epam/esm/controller/CertificateController.java
> +    @RequestMapping(value = "/{id}", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
It would be also great to use static imports for constants

2020-10-29 09:02 UTC, Pickle9 commented on api/src/main/java/com/epam/esm/dao/CertificateDao.java
> +    List<Certificate> getAllCertificates();
There is no necessity to duplicate 'certificate' in every method name. This is CertificateDao, it's obvious which object we are working with

2020-10-29 09:02 UTC, Pickle9 commented on api/src/main/java/com/epam/esm/dao/mapper/CertificateExtractor.java
> +import static com.epam.esm.dao.mapper.MapperConstant.*;
It's not really the best practice to use *. You should import each one separately

2020-10-29 09:02 UTC, Pickle9 commented on api/src/main/java/com/epam/esm/dto/CertificateDto.java
> +    private static final String DATE_TIME_TIMEZONE = "UTC";
It would be great to separate the constants and fields themselves

2020-10-29 09:02 UTC, Pickle9 commented on api/src/main/java/com/epam/esm/service/impl/TagServiceImpl.java
> +            Tag byName = tagDao.getByName(tag.getName());
Personally, I would not throw an exception in the dao layout if the entity not found. Throwing an exception is so expensive, so, null is a more appropriate result. Then exception may be thrown from the service layout if needed.

2020-10-29 09:02 UTC, Pickle9 commented on api/src/main/java/com/epam/esm/service/validation/impl/CertificateValidatorImpl.java
> +            return certificateDto.getName().length() < NAME_SIZE
As for me, it's more preferable to use Java Bean Validation and Spring Validator in this task (Hibernate is forbidden as a JPA, but not as a Validation provider). So, just try to use this solution here or in the next task.
Talking about the current case, validator should return a more informative response, such as a list of errors or something like that. Another point, the whole entity must be validated. Check all fields and return all errors.

2020-10-29 09:02 UTC, Pickle9 commented on api/src/test/java/com/epam/esm/dao/CertificateDaoImplTest.java
> +    public void setUp() {
There is no necessity to configure these fields before each test. It takes a lot of time and can be initialized ones.
By the way, you don't need to initialize all of these classes manually. Spring is your bean provider, so, it can be handled by him.

2020-10-29 09:02 UTC, Pickle9 commented on api/src/main/java/com/epam/esm/dto/CertificateDto.java
> +public class CertificateDto {
It's also a good practice to make a constructor that will transform the original entity to the dto object.

2020-10-29 09:02 UTC, Pickle9 commented on api/src/test/java/com/epam/esm/service/CertificateServiceTest.java
> +        Certificate certificate = Certificate.builder().id(1L).name("name").description("description")
Unit tests should be simple, clear, and fast. So, use separate methods for creating an object and mocking calls.

2020-10-29 09:02 UTC, Pickle9 commented on pom.xml
> +        <dependency>
We must use a 5+ version of JUnit. This dependency must be also deleted from the 'api' pom

2020-10-29 09:02 UTC, Pickle9 commented on api/src/main/java/com/epam/esm/exception/ResourceNotFoundException.java
> +public class ResourceNotFoundException extends RuntimeException implements Serializable {
Is Lombok not allowed here?

2020-10-29 09:02 UTC, Pickle9 commented on api/src/main/java/com/epam/esm/dao/impl/CertificateDaoImpl.java
> +            stringBuilder.append(" AND tag.name = '").append(filter.getTagName()).append("'");
To be honest, this looks not really fine. At least you should use prepared statements for avoiding the sql injections.

2020-10-30 12:31 UTC, natashlapakova commented on api/src/main/java/com/epam/esm/dao/TagDao.java
> +
Let's create interface with general methods for Daos

2020-11-09 08:52 UTC, merged